name: Daily run
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - generate.py
jobs:
  daily-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Installs Poetry
        uses: Gr1N/setup-poetry@v8
      - name: Install the dependencies
        run: poetry install
      - name: Update the feeds
        run: |
          poetry run python3 generate.py 01.01.2024
      - name: Commit the changes
        run: |
          git add cache/ feeds/
          git config --global user.name "RSS feeds updater"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "Updates the feeds"
          git push

